version: '2'
services:
  dev:
    container_name: dev
    build: .
    ports:
      - '2222:22'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'home:/root'
    restart: always

volumes:
  home:
    driver: local
