version: '2'
services:
  dev:
    container_name: dev
    build: .
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'home:/root'
    network_mode: host
    restart: always

volumes:
  home:
    driver: local
